# Generated by Django 2.2.12 on 2021-07-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshop', '0002_product_add_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='add_image1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='add_image2',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
