# Generated by Django 2.2.12 on 2021-07-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
