# Generated by Django 2.2.12 on 2021-07-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
