# Generated by Django 2.2.12 on 2021-07-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
