# Generated by Django 2.2.12 on 2021-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210718_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
