# Generated by Django 2.2.12 on 2021-07-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210718_0517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
