# Generated by Django 2.2.12 on 2021-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
