# Generated by Django 2.2.12 on 2021-07-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20210718_0520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
