# Generated by Django 2.2.12 on 2021-07-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='address',
            name='price',
        ),
    ]
