# Generated by Django 2.2.12 on 2021-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=8),
        ),
    ]
