# Generated by Django 2.2.12 on 2021-07-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20210718_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='price',
        ),
    ]
