# Generated by Django 2.2.12 on 2021-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20210718_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
