# Generated by Django 2.2.12 on 2021-07-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_auto_20210718_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='items',
            field=models.TextField(),
        ),
    ]
