# Generated by Django 2.2.12 on 2021-07-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_auto_20210718_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='cash_on_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
