# Generated by Django 2.2.12 on 2021-07-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_useraddress_ad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='ad_id',
        ),
    ]
